name: Deploy a docker image
description: Deploy a docker image

inputs:
  image:
    description: The image to deploy.
    required: true
    default: ""

  host:
    description: |
      The host under which to deploy the image.

      If the host contains "*" it will be replaced by the full deployment name.
    required: true
    default: ""

  env:
    description: |
      A comma separated list of environment variable names to provide to the container.
    required: false
    default: ""

  app:
    description: |
      The name of the app.

      If no name is given it will be set to the docker image name (without leading namespaces).
    required: false
    default: ""

  release:
    description: |
      The name of the release.

      If no release is given it will be set to the docker image tag.
    required: false
    default: ""

  namespace:
    description: |
      The namespace to deploy into.

      If no namespace is given, it defaults to `default`.
    required: false
    default: ""

  port:
    description: The port to expose from the image.
    required: false
    default: "80"

  docker_secret:
    description: The secret to use to pull images.
    required: false

  digitalocean_token:
    description: The digitalocean token, if you are deploying to digitalocean.
    required: false

  digitalocean_cluster:
    description: The name of the digitalocean_cluster if you are deploying to digitalocean.
    required: false

  undeploy:
    description: Whether or not to undeploy instead of deploy the container.
    required: false
    default: "false"

  enable_commit_comment:
    description: Whether or not to add a comment to the commit with the deployment information.
    required: false
    default: "false"

  github_token:
    description: The github token used to create the commit comment.
    required: false

  values_file:
    description: Path to a yaml file that will be used to provide configuration values for the internal helm chart. See the [./k8s/helm](Chart) for more information.
    required: false

branding:
  icon: "gift"
  color: "blue"

runs:
  using: "node12"
  main: "dist/index.js"
