apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "chart.fullname" . }}"
  namespace: "{{ .Values.namespace . }}"
  labels:
    app: "{{ .Values.app }}"
    release: "{{ .Values.release }}"
{{ include "chart.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app: "{{ .Values.app }}"
      release: "{{ .Values.release }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.app }}"
        release: "{{ .Values.release }}"
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: "{{ include "chart.fullname" . }}"
        image: "{{ .Values.image }}"
        env:
        - name: HOST
          value: https://{{ .Values.host }}
{{ range $key, $value := .Values.env }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
{{ end }}
        ports:
        - containerPort: {{ .Values.port }}
