apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "chart.fullname" . }}"
  labels:
{{ include "chart.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app: "{{ .Values.app }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.app }}"
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: "{{ include "chart.fullname" . }}"
        image: "{{ .Values.image }}"
        env:
        - name: HOST
          value: https://{{ .Values.host }}
        - name: NODE_ENV
          value: {{ .Values.env }}
        ports:
        - containerPort: {{ .Values.port }}
