apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ include "chart.fullname" . }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: "{{ .Values.app }}"
    release: "{{ .Values.release }}"
{{ include "chart.labels" . | indent 4 }}
{{- with .Values.ingress.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
{{- end }}
spec:
  rules:
    - host: "{{ .Values.host }}"
      http:
        paths:
          - path: /
            backend:
              service:
                name: "{{ include "chart.fullname" . }}"
                port:
                  number: {{ .Values.port }}
