apiVersion: v1
kind: Service
metadata:
  name: "{{ include "chart.fullname" . }}"
  namespace: "{{ .Values.namespace . }}"
  labels:
    app: "{{ .Values.app }}"
    release: "{{ .Values.release }}"
{{ include "chart.labels" . | indent 4 }}
spec:
  type: NodePort
  selector:
    app: "{{ .Values.app }}"
    release: "{{ .Values.release }}"
  ports:
  - port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
